name: Docker Build and Run Log Monitor

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image
      run: docker build -t log-monitor .

    - name: Run container (test)
      run: |
        mkdir log_output
        docker run -v ${{ github.workspace }}/log_output:/log_output log-monitor
        ls log_output
